sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: gradle setupCIWorkspace
script: gradle build
notifications:
  email: false